version: "3.8"
services:
  client-app:
    image: client-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: backend-server
    ports:
      - "5000:5000"
    networks:
      - db-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - db-app
    volumes:
      - db-data:/data/db
networks:
  db-app:
    driver: bridge
volumes:
  db-data:
    driver: local
